### PR TITLE
README.md: Link IRC channel

### PR DESCRIPTION
**Pull request by reedy**

### CODE REVIEW

**Comment by Arkiver2** [comment]
Can you please change that to be the same way as in the last line in https://github.com/ArchiveTeam/standalone-readme-template/blob/master/README.wget-at.md?

**Comment by reedy** [comment]
> Can you please change that to be the same way as in the last line in https://github.com/ArchiveTeam/standalone-readme-template/blob/master/README.wget-at.md?

The whole line? Or just the IRC channel link part?

**Comment by Arkiver2** [comment]
I would say the IRC channel link part and the explicit mention of hackint IRC. The problem with an non-HTTP IRC URL is that it'll be hard for many people to get in contact as they don't have an IRC client set up.

**Comment by Arkiver2** [comment]
Thank you!

**Pull request merged**
